apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: donet-app-14
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: donet-app-14
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/kadourah/dotnetapp14
      ref:
        branch: main
